### ISSUE TITLE
could not load FFI provider jnr.ffi.provider.jffi.Provider

### ISSUE THREAD

**Issue by ravelsk** [jnr/jnr-ffi#155]
Project is build in NetBeans 8.0.2 .
In attachment is full project including used dll in project root dir. Project is run on Windows 7-64b and 32bit Java runtime jre1.8.0_144. Used dll is too 32bit and is part of Hikvision SDK.

[HVTest2.zip](https://github.com/jnr/jnr-ffi/files/1575582/HVTest2.zip)

**Comment by moaxcp** [comment]
I just ran into something similar. Here is a simple groovy script I'm running on nixos.

```groovy
#!/usr/bin/env groovy
 
@Grapes(  
    @Grab(group='com.github.jnr', module='jnr-ffi', version='2.1.7')
)

import jnr.ffi.LibraryLoader 

public interface GetPid {
    long getpid()
}

GetPid getpid = LibraryLoader.create(GetPid).load('c')
println getpid.getpid()
```
The full exception is

```
Caught: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:48)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
        at jnr.ffi.LibraryLoader$load$0.call(Unknown Source)
        at pid.run(pid.groovy:13)
Caused by: java.lang.NoClassDefFoundError: com/kenai/jffi/Type
        at jnr.ffi.provider.jffi.NativeRuntime.jafflType(NativeRuntime.java:202)
        at jnr.ffi.provider.jffi.NativeRuntime.buildTypeMap(NativeRuntime.java:85)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
        at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
        at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
        at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
        at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
        at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
        at jnr.ffi.LibraryLoader$create.call(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.kenai.jffi.Type
        ... 13 more
```

**Comment by ravelsk** [comment]
O.K. Thank You for help. I now use JNA. I am software programmer a long time. When i prepare library for 3rd party ma client expected, that use my library is without problem and of various curiosities. If programmer must 5 day seek for errors from 3rd library and nothing is solved he spurn this library.
More success....

**Comment by headius** [comment]
Sorry this one slipped through! Is it possible you have two conflicting versions of jnr-ffi?

**Comment by moaxcp** [comment]
The groovy script should only use 2.1.7. It is the only dependency declared.
